import { createFileRoute, Link } from "@tanstack/react-router";
import { useState, useEffect } from "react";
import { useVisualMode } from "~/hooks/useVisualMode";
import { useAuth } from "~/hooks/useAuth";
import { listJobs, createJob, deleteJob, removePartFromJob } from "~/utils/jobs";
import { queueEmail } from "~/routes/api/email";
import { AuthModal } from "~/components/AuthModal";
import type { Job, SavedPart } from "~/utils/jobs";

export const Route = createFileRoute("/jobs")({
  component: JobsPage,
});

const MODE_ICONS: Record<string, string> = { normal: "☀️", dark: "🌙", "high-contrast": "🔲", calm: "🌀" };
const MODE_LABELS: Record<string, string> = { normal: "Light mode", dark: "Dark mode", "high-contrast": "High contrast", calm: "Calm mode" };

function JobsPage() {
  const { mode, cycleMode } = useVisualMode();
  const { user, showAuth, setShowAuth, saveSession, clearSession } = useAuth();
  const [jobs, setJobs] = useState<Job[]>([]);
  const [loading, setLoading] = useState(true);
  const [showCreate, setShowCreate] = useState(false);
  const [newName, setNewName] = useState("");
  const [newNotes, setNewNotes] = useState("");
  const [exporting, setExporting] = useState<string | null>(null);
  const [exportMsg, setExportMsg] = useState("");

  useEffect(() => {
    if (user) {
      setLoading(true);
      listJobs({ data: { userId: user.id } }).then((r) => {
        if (r.ok) setJobs(r.jobs!);
        setLoading(false);
      });
    } else {
      setLoading(false);
    }
  }, [user]);

  const handleCreate = async () => {
    if (!user || !newName.trim()) return;
    const r = await createJob({ data: { userId: user.id, name: newName.trim(), notes: newNotes.trim() } });
    if (r.ok && r.job) {
      setJobs((prev) => [...prev, r.job!]);
      setShowCreate(false);
      setNewName("");
      setNewNotes("");
    }
  };

  const handleDelete = async (jobId: string) => {
    if (!user) return;
    const r = await deleteJob({ data: { userId: user.id, jobId } });
    if (r.ok) setJobs((prev) => prev.filter((j) => j.id !== jobId));
  };

  const handleRemovePart = async (jobId: string, partIndex: number) => {
    if (!user) return;
    const r = await removePartFromJob({ data: { userId: user.id, jobId, partIndex } });
    if (r.ok && r.job) {
      setJobs((prev) => prev.map((j) => (j.id === jobId ? r.job! : j)));
    }
  };

  const handleExport = async (job: Job) => {
    setExporting(job.id);
    setExportMsg("");
    try {
      const partLines = job.parts.map((p, i) =>
        `${i + 1}. ${p.partNumber} (${p.manufacturer} - ${p.series})\n   Function: ${p.function}, Finish: ${p.finish}, Keyway: ${p.keyway}${p.pins ? `, Pins: ${p.pins}` : ""}, Handing: ${p.handing}, Backset: ${p.backset}${p.notes ? `\n   Notes: ${p.notes}` : ""}`
      ).join("\n\n");
      const emailBody = `LockBuilder Job Export\n${"=".repeat(40)}\n\nJob: ${job.name}\n${job.notes ? `Notes: ${job.notes}\n` : ""}Created: ${new Date(job.createdAt).toLocaleDateString()}\nTotal Parts: ${job.parts.length}\n\n${"=".repeat(40)}\nPARTS LIST\n${"=".repeat(40)}\n\n${partLines || "No parts in this job."}\n\n${"=".repeat(40)}\nGenerated by LockBuilder`;

      const result = await queueEmail({
        data: {
          to: user.email,
          subject: `LockBuilder Job: ${job.name}`,
          body: emailBody,
        },
      });
      if (result.ok) {
        setExportMsg("✅ Email queued! The system will send it shortly.");
      } else {
        setExportMsg(`❌ ${result.error || "Failed to queue"}`);
      }
    } catch (err) {
      setExportMsg("❌ Failed to prepare email");
    }
    setTimeout(() => setExportMsg(""), 5000);
    setExporting(null);
  };

  const cardStyle = {
    backgroundColor: "var(--bg-secondary)",
    border: "1px solid var(--border-color)",
    borderRadius: "12px",
    padding: "16px",
  };

  const inputStyle: React.CSSProperties = {
    width: "100%", padding: "12px 14px", borderRadius: "8px", fontSize: "16px",
    backgroundColor: "var(--bg-primary)", color: "var(--text-primary)",
    border: "1px solid var(--border-color)", outline: "none",
    minHeight: "48px", marginBottom: "8px",
  };

  if (!user) {
    return (
      <div className="mx-auto max-w-2xl px-4 py-8 text-center">
        <h2 className="text-xl font-bold mb-4" style={{ color: "var(--text-primary)" }}>My Jobs</h2>
        <p className="mb-4 text-sm" style={{ color: "var(--text-muted)" }}>Sign in to save and manage your jobs.</p>
        <button onClick={() => setShowAuth(true)}
          className="rounded-lg px-6 py-3 text-sm font-medium text-white" style={{ backgroundColor: "var(--accent)", border: "none", cursor: "pointer" }}>
          Sign In
        </button>
        {showAuth && <AuthModal onClose={() => setShowAuth(false)} onSuccess={saveSession} />}
        <footer className="mt-8 text-xs" style={{ color: "var(--text-muted)" }}>
          <Link to="/" className="hover:underline" style={{ color: "var(--accent)" }}>Back to builder</Link>
        </footer>
      </div>
    );
  }

  return (
    <div className="mx-auto max-w-3xl px-4 py-5 sm:px-6 sm:py-8">
      {/* Header */}
      <header className="mb-6 flex items-center justify-between">
        <Link to="/" className="flex items-center gap-3 no-underline">
          <div className="flex h-10 w-10 items-center justify-center rounded-lg text-lg font-bold text-white shadow-sm"
            style={{ backgroundColor: mode === "high-contrast" ? "#000" : mode === "calm" ? "#6B6B6B" : "#1B2A4A" }}>
            LB
          </div>
          <div>
            <h1 className="text-xl font-bold" style={{ color: "var(--text-primary)" }}>My Jobs</h1>
            <p className="text-xs" style={{ color: "var(--text-muted)" }}>{user.name}</p>
          </div>
        </Link>
        <div className="flex items-center gap-2">
          <button onClick={() => setShowCreate(true)}
            className="mode-toggle-btn font-bold" title="Create new job" aria-label="Create new job">
            <span className="text-lg">+</span>
          </button>
          <button className="mode-toggle-btn" onClick={cycleMode} title={MODE_LABELS[mode]}>
            <span className="text-base">{MODE_ICONS[mode]}</span>
          </button>
        </div>
      </header>

      {/* Create Job Form */}
      {showCreate && (
        <div className="mb-6" style={cardStyle}>
          <h3 className="font-semibold mb-3" style={{ color: "var(--text-primary)" }}>New Job</h3>
          <input style={inputStyle} placeholder="Job name" value={newName}
            onChange={(e) => setNewName(e.target.value)} />
          <input style={inputStyle} placeholder="Notes (optional)" value={newNotes}
            onChange={(e) => setNewNotes(e.target.value)} />
          <div className="flex gap-2">
            <button onClick={handleCreate}
              className="rounded-lg px-4 py-2 text-sm font-medium text-white"
              style={{ backgroundColor: "var(--accent)", border: "none", cursor: "pointer", minHeight: "44px" }}>
              Create
            </button>
            <button onClick={() => setShowCreate(false)}
              className="rounded-lg px-4 py-2 text-sm"
              style={{ backgroundColor: "var(--bg-tertiary)", color: "var(--text-secondary)", border: "none", cursor: "pointer", minHeight: "44px" }}>
              Cancel
            </button>
          </div>
        </div>
      )}

      {/* Export message */}
      {exportMsg && (
        <div className="mb-4 text-sm" style={{ color: exportMsg.includes("✅") ? "var(--success)" : "#d32f2f" }}>
          {exportMsg}
        </div>
      )}

      {/* Jobs List */}
      {loading ? (
        <p className="text-sm" style={{ color: "var(--text-muted)" }}>Loading...</p>
      ) : jobs.length === 0 ? (
        <div className="rounded-xl border border-dashed p-8 text-center" style={{ borderColor: "var(--border-color)" }}>
          <p className="text-sm" style={{ color: "var(--text-muted)" }}>No jobs yet. Create one or save a part from the builder.</p>
        </div>
      ) : (
        <div className="space-y-4">
          {jobs.map((job) => (
            <div key={job.id} style={cardStyle}>
              <div className="flex items-start justify-between mb-2">
                <div>
                  <h3 className="font-semibold" style={{ color: "var(--text-primary)" }}>{job.name}</h3>
                  {job.notes && <p className="text-xs mt-0.5" style={{ color: "var(--text-muted)" }}>{job.notes}</p>}
                </div>
                <div className="flex items-center gap-1 shrink-0">
                  <span className="text-xs px-2 py-1 rounded" style={{ backgroundColor: "var(--bg-tertiary)", color: "var(--text-muted)" }}>
                    {job.parts.length} parts
                  </span>
                </div>
              </div>

              {/* Parts list */}
              {job.parts.length > 0 && (
                <div className="space-y-1 mb-3">
                  {job.parts.map((part, idx) => (
                    <div key={idx} className="flex items-center justify-between rounded px-3 py-2 text-xs"
                      style={{ backgroundColor: "var(--bg-tertiary)" }}>
                      <div className="min-w-0 flex-1">
                        <span className="font-medium" style={{ color: "var(--text-primary)" }}>{part.partNumber}</span>
                        <span className="ml-2" style={{ color: "var(--text-muted)" }}>{part.manufacturer} — {part.series}</span>
                        {part.pins && (
                          <span className="ml-2" style={{ color: "var(--text-muted)" }}>{part.pins}-pin</span>
                        )}
                      </div>
                      <button onClick={() => handleRemovePart(job.id, idx)}
                        className="text-xs ml-2" style={{ color: "var(--text-muted)", background: "none", border: "none", cursor: "pointer" }}>
                        ✕
                      </button>
                    </div>
                  ))}
                </div>
              )}

              <div className="flex items-center gap-2 mt-3">
                <button onClick={() => handleExport(job)}
                  className="rounded-lg px-3 py-1.5 text-xs font-medium"
                  style={{
                    backgroundColor: "color-mix(in srgb, var(--accent) 10%, transparent)",
                    color: "var(--accent)", border: "none", cursor: exporting === job.id ? "wait" : "pointer",
                    minHeight: "36px",
                  }}>
                  {exporting === job.id ? "Sending..." : "📧 Export as Email"}
                </button>
                <button onClick={() => handleDelete(job.id)}
                  className="rounded-lg px-3 py-1.5 text-xs"
                  style={{ backgroundColor: "var(--bg-tertiary)", color: "var(--text-muted)", border: "none", cursor: "pointer", minHeight: "36px" }}>
                  Delete
                </button>
              </div>

              <p className="mt-2 text-xs" style={{ color: "var(--text-muted)" }}>
                Created {new Date(job.createdAt).toLocaleDateString()}
              </p>
            </div>
          ))}
        </div>
      )}

      <footer className="mt-10 border-t pt-5 text-center text-xs"
        style={{ borderColor: "var(--border-color)", color: "var(--text-muted)" }}>
        <Link to="/" className="hover:underline" style={{ color: "var(--accent)" }}>Back to builder</Link>
      </footer>
    </div>
  );
}